apiVersion: v1
kind: ServiceAccount
metadata:
  name: costq-fastapi-sa
  namespace: costq-fastapi
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::000451883532:role/costq-eks-service-account-role
  labels:
    app: costq-fastapi
    environment: production
